# Generated by Django 5.2.17 on 2026-10-01 13:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('foto', models.ImageField(blank=True, upload_to='produtos/', verbose_name='foto')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='catalogo.categoria', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='OpcaoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(choices=[('MACO', 'Maço'), ('KG', 'Quilo')], max_length=4, verbose_name='unidade')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço por maço ou por quilo, conforme a unidade selecionada.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='preço (R$)')),
                ('disponivel', models.BooleanField(default=True, verbose_name='disponível')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes_venda', to='catalogo.produto', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'opção de venda',
                'verbose_name_plural': 'opções de venda',
                'ordering': ['produto__nome', 'unidade'],
                'constraints': [models.UniqueConstraint(fields=('produto', 'unidade'), name='catalogo_produto_unidade_unicos'), models.CheckConstraint(condition=models.Q(('preco__gt', 0)), name='catalogo_preco_positivo'), models.CheckConstraint(condition=models.Q(('unidade__in', ['MACO', 'KG'])), name='catalogo_unidade_valida')],
            },
        ),
    ]
