# Generated by Django 5.2.17 on 2026-10-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='opcaovenda',
            name='catalogo_produto_unidade_unicos',
        ),
        migrations.AddField(
            model_name='opcaovenda',
            name='preparo',
            field=models.CharField(blank=True, max_length=30, verbose_name='preparo'),
        ),
        migrations.AddConstraint(
            model_name='opcaovenda',
            constraint=models.UniqueConstraint(fields=('produto', 'unidade', 'preparo'), name='catalogo_produto_unidade_preparo_unicos'),
        ),
    ]
