# Generated by Django 5.2.17 on 2026-10-01 13:42

import django.core.validators
import django.db.models.deletion
import pedidos.models
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(blank=True, help_text='Somente números: 55 + DDD + telefone.', max_length=13, validators=[pedidos.models.validar_whatsapp], verbose_name='WhatsApp do vendedor')),
                ('regiao_entrega', models.CharField(blank=True, help_text='Texto exibido ao cliente. A disponibilidade será confirmada pelo vendedor.', max_length=300, verbose_name='informações sobre a região de entrega')),
            ],
            options={
                'verbose_name': 'configuração da loja',
                'verbose_name_plural': 'configuração da loja',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default=pedidos.models.gerar_numero, editable=False, max_length=14, unique=True, verbose_name='número')),
                ('chave_checkout', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sessao_hash', models.CharField(editable=False, max_length=64)),
                ('nome_cliente', models.CharField(max_length=120, verbose_name='nome')),
                ('telefone_cliente', models.CharField(max_length=13, verbose_name='telefone / WhatsApp')),
                ('modalidade', models.CharField(choices=[('ENTREGA', 'Entrega'), ('RETIRADA', 'Retirada')], max_length=8, verbose_name='recebimento')),
                ('forma_pagamento', models.CharField(choices=[('CARTAO', 'Cartão'), ('PIX', 'Pix'), ('DINHEIRO', 'Dinheiro')], max_length=8, verbose_name='forma de pagamento')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=180, verbose_name='rua / avenida')),
                ('numero_endereco', models.CharField(blank=True, max_length=20, verbose_name='número (ou S/N)')),
                ('complemento', models.CharField(blank=True, max_length=120, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('referencia', models.CharField(blank=True, max_length=200, verbose_name='ponto de referência')),
                ('observacoes', models.TextField(blank=True, max_length=1000, verbose_name='observações do cliente')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de confirmação'), ('CONFIRMADO', 'Confirmado'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10, verbose_name='status')),
                ('subtotal_produtos', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='subtotal dos produtos')),
                ('taxa_entrega', models.DecimalField(blank=True, decimal_places=2, help_text='Em branco: a combinar. Zero: sem cobrança de entrega.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='taxa de entrega')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-criado_em'],
                'constraints': [models.CheckConstraint(condition=models.Q(('subtotal_produtos__gte', 0)), name='pedido_subtotal_nao_negativo'), models.CheckConstraint(condition=models.Q(('taxa_entrega__isnull', True), ('taxa_entrega__gte', 0), _connector='OR'), name='pedido_taxa_nao_negativa'), models.CheckConstraint(condition=models.Q(('modalidade', 'ENTREGA'), models.Q(('modalidade', 'RETIRADA'), ('taxa_entrega', 0), ('taxa_entrega__isnull', False)), _connector='OR'), name='pedido_retirada_taxa_zero')],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=150, verbose_name='produto')),
                ('unidade', models.CharField(choices=[('MACO', 'Maço'), ('KG', 'Quilo')], max_length=4, verbose_name='unidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço unitário')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='quantidade solicitada')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='subtotal')),
                ('opcao_venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedidos', to='catalogo.opcaovenda')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'item do pedido',
                'verbose_name_plural': 'itens do pedido',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='item_quantidade_positiva'), models.CheckConstraint(condition=models.Q(('preco_unitario__gt', 0)), name='item_preco_positivo'), models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='item_subtotal_nao_negativo')],
            },
        ),
    ]
