# Generated by Django 5.2.17 on 2026-10-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoloja',
            name='cidade_entrega',
            field=models.CharField(blank=True, max_length=100, verbose_name='cidade atendida'),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='uf_entrega',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF atendida'),
        ),
    ]
